[package]
edition = "2021"
name = "check_api_contract"
version = "0.1.0"

[dependencies]
reqwest = {version = "0.12.4", features = ["blocking"]}
serde = {version = "1.0.202", features = ["std", "derive"]}
serde_json = "1.0.117"
